### ISSUE TITLE
Request to turn the separate .yaml files into a one package.yaml

### ISSUE THREAD

**Issue by WheezyE** [nvanggaard/clockalarm#10]
I recently discovered HASS has a "package" option for including multiple headers along with code.  I've put all your HASS code into one file and set up my configuration.yaml as follows and it works great and looks clean.

_(ok, full disclosure: I haven't actually tested with scenes, but it works for my HASS scripts when I change your python script's line 43 and 45 from "homeassistant" to "script")_

homeassistant\configuration.yaml
```yaml
homeassistant:
[...lots of code here...]
  packages: 
    pack_1: !include clockalarm_package.yaml
[...lots more code down here...]
```

homeassistant\clockalarm_package.yaml
```yaml
#Clock alarm: Custom component from https://github.com/nvanggaard/clockalarm
#   https://community.home-assistant.io/t/create-alarm-clock/1307/2
clockalarm:
    entity_id: scene.eggs_and_bakey
    device_home: device_tracker.YOUR_TRACKER_NUMBER_HERE

homeassistant:
    customize:
      group.alarm:
        friendly_name: Alarm Clock
      input_select.wake_up_time:
        icon: mdi:alarm
      input_boolean.monday:
        icon: mdi:calendar-today
      input_boolean.tuesday:
        icon: mdi:calendar-today
      input_boolean.wednesday:
        icon: mdi:calendar-today
      input_boolean.thursday:
        icon: mdi:calendar-today
      input_boolean.friday:
        icon: mdi:calendar-today
      input_boolean.saturday:
        icon: mdi:calendar-today
      input_boolean.sunday:
        icon: mdi:calendar-today
        
input_boolean: 
    # Makes a button to control automated home
    monday:
      name: Monday
      initial: on
    tuesday:
      name: Tuesday
      initial: on
    wednesday:
      name: Wednesday
      initial: on
    thursday:
      name: Thursday
      initial: on
    friday:
      name: Friday
      initial: on
    saturday:
      name: Saturday
      initial: off
    sunday:
      name: Sunday
      initial: off

      
input_select:
    wake_up_time:
      name: Set alarm
      initial: "07:00"
      options:
        - "00:00"
        - "00:15"
        - "00:30"
        - "00:45"
        - "01:00"
        - "01:15"
        - "01:30"
        - "01:45"
        - "02:00"
        - "02:15"
        - "02:30"
        - "02:45"
        - "03:00"
        - "03:15"
        - "03:30"
        - "03:45"
        - "04:00"
        - "04:15"
        - "04:30"
        - "04:45"
        - "05:00"
        - "05:15"
        - "05:30"
        - "05:45"
        - "06:00"
        - "06:15"
        - "06:30"
        - "06:45"
        - "07:00"
        - "07:15"
        - "07:30"
        - "07:45"
        - "08:00"
        - "08:15"
        - "08:30"
        - "08:45"
        - "09:00"
        - "09:15"
        - "09:30"
        - "09:45"
        - "10:00"
        - "10:15"
        - "10:30"
        - "10:45"
        - "11:00"
        - "11:15"
        - "11:30"
        - "11:45"
        - "12:00"
        - "12:15"
        - "12:30"
        - "12:45"
        - "13:00"
        - "13:15"
        - "13:30"
        - "13:45"
        - "14:00"
        - "14:15"
        - "14:30"
        - "14:45"
        - "15:00"
        - "15:15"
        - "15:30"
        - "15:45"
        - "16:00"
        - "16:15"
        - "16:30"
        - "16:45"
        - "17:00"
        - "17:15"
        - "17:30"
        - "17:45"
        - "18:00"
        - "18:15"
        - "18:30"
        - "18:45"
        - "19:00"
        - "19:15"
        - "19:30"
        - "19:45"
        - "20:00"
        - "20:15"
        - "20:30"
        - "20:45"
        - "21:00"
        - "21:15"
        - "21:30"
        - "21:45"
        - "22:00"
        - "22:15"
        - "22:30"
        - "22:45"
        - "23:00"
        - "23:15"
        - "23:30"
        - "23:45"
        
group:
    alarm:
      - input_select.wake_up_time
      - input_select.transition_time
      - input_boolean.monday
      - input_boolean.tuesday
      - input_boolean.wednesday
      - input_boolean.thursday
      - input_boolean.friday
      - input_boolean.saturday
      - input_boolean.sunday
```
